config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, :content, presence: true
  validates :rating, inclusion: 0..5
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    @review.save
    if @review.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@movie, @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
   <%= f.association :movie %>
  <%= f.submit "create", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>


  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://rimage.gnst.jp/livejapan.com/public/article/detail/a/00/00/a0000430/img/basic/a0000430_main.jpg?20170429124716&q=80&rw=750&rh=536);">
  <div class="container">
    <h1>Save any kind of Movies</h1>
  </div>
</div>

  <h2>My Lists</h2>

<div class="container list-container">



  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>');">
        <%= list.name %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/lists/new.html.erb
<%= simple_form_for [ @list ] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "create list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="button-movie">
    <%= link_to 'add a movie', new_list_bookmark_path(@list), class: "btn btn-dark rounded"  %>
</div>


<div class="container list-container" data-aos="fade-up">

    <% @bookmarks.each do |bookmark| %>
      <div class="card col-md-4" style="width: 24rem;">
          <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="Card image cap">
          <div class="card-body">
            <h2><%= bookmark.movie.title %></h2>
              <p><%= bookmark.movie.overview %></p>
              <p><%= bookmark.movie.rating%></p>
              <p><%= bookmark.comment %></p>
          </div>
            <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>


  </div>

<div class="button-movie">
  <%= link_to "Delete list", list_path(@list), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</div>



  <h2>Reviews</h2>

  <% @list.reviews.each do |review|%>

    <div class="card-product">
      <div class="card-product-infos">
        <h2><%= review.rating %></h2>
         <p><%= review.content %></p>
      </div>
    </div>
  <% end %>

<div class="button-footer">
  <%= link_to 'add a review', new_list_review_path(@list),class: 'btn btn-info' %>

  <%= link_to 'go back', root_path ,class: 'btn btn-primary'%>
</div>

app/views/movies/new.html.erb
 <%= simple_form_for [ @movie ] do |f| %>
      <%= f.input :title %>
      <%= f.input :overview %>
      <%= f.input :rating %>
      <%= f.input :poster_url %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

app/views/reviews/new.html.erb
<h1>Add a New Review</h1>

<%= simple_form_for [@list, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "send review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
      <%= link_to root_path ,class:"navbar-brand" do%>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTRj0RyADJQSDqFuE6Moh5SjE5P2BGJ4G8QC0J06bhzu8k5jEGvBJBJQ2muJCa_RC1HJI&usqp=CAU" />
      <% end %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'new list', new_list_path, class:"nav-link"  %>
          </li>

      </ul>
    </div>
  </div>
</div>